name: Update DevCard
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch DevCard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}

      - name: Debug File Format
        run: |
          file /tmp/devcard.png
          ls -lh /tmp/devcard.png
